// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/message"
	"server/ent/schema"
	"server/ent/userslist"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescRoomID is the schema descriptor for room_id field.
	messageDescRoomID := messageFields[1].Descriptor()
	// message.RoomIDValidator is a validator for the "room_id" field. It is called by the builders before save.
	message.RoomIDValidator = messageDescRoomID.Validators[0].(func(string) error)
	// messageDescUsername is the schema descriptor for username field.
	messageDescUsername := messageFields[2].Descriptor()
	// message.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	message.UsernameValidator = messageDescUsername.Validators[0].(func(string) error)
	// messageDescText is the schema descriptor for text field.
	messageDescText := messageFields[3].Descriptor()
	// message.TextValidator is a validator for the "text" field. It is called by the builders before save.
	message.TextValidator = messageDescText.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[4].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	userslistFields := schema.UsersList{}.Fields()
	_ = userslistFields
	// userslistDescUsername is the schema descriptor for username field.
	userslistDescUsername := userslistFields[1].Descriptor()
	// userslist.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	userslist.UsernameValidator = userslistDescUsername.Validators[0].(func(string) error)
	// userslistDescEmail is the schema descriptor for email field.
	userslistDescEmail := userslistFields[2].Descriptor()
	// userslist.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	userslist.EmailValidator = userslistDescEmail.Validators[0].(func(string) error)
	// userslistDescPassword is the schema descriptor for password field.
	userslistDescPassword := userslistFields[3].Descriptor()
	// userslist.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	userslist.PasswordValidator = userslistDescPassword.Validators[0].(func(string) error)
	// userslistDescID is the schema descriptor for id field.
	userslistDescID := userslistFields[0].Descriptor()
	// userslist.DefaultID holds the default value on creation for the id field.
	userslist.DefaultID = userslistDescID.Default.(func() uuid.UUID)
}
