// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/predicate"
	"server/ent/userslist"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsersListUpdate is the builder for updating UsersList entities.
type UsersListUpdate struct {
	config
	hooks    []Hook
	mutation *UsersListMutation
}

// Where appends a list predicates to the UsersListUpdate builder.
func (_u *UsersListUpdate) Where(ps ...predicate.UsersList) *UsersListUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoomID sets the "room_id" field.
func (_u *UsersListUpdate) SetRoomID(v string) *UsersListUpdate {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *UsersListUpdate) SetNillableRoomID(v *string) *UsersListUpdate {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UsersListUpdate) SetUsername(v string) *UsersListUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UsersListUpdate) SetNillableUsername(v *string) *UsersListUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UsersListUpdate) SetEmail(v string) *UsersListUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UsersListUpdate) SetNillableEmail(v *string) *UsersListUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UsersListUpdate) SetPassword(v string) *UsersListUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UsersListUpdate) SetNillablePassword(v *string) *UsersListUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// Mutation returns the UsersListMutation object of the builder.
func (_u *UsersListUpdate) Mutation() *UsersListMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsersListUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsersListUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsersListUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsersListUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsersListUpdate) check() error {
	if v, ok := _u.mutation.RoomID(); ok {
		if err := userslist.RoomIDValidator(v); err != nil {
			return &ValidationError{Name: "room_id", err: fmt.Errorf(`ent: validator failed for field "UsersList.room_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := userslist.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UsersList.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := userslist.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UsersList.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := userslist.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "UsersList.password": %w`, err)}
		}
	}
	return nil
}

func (_u *UsersListUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userslist.Table, userslist.Columns, sqlgraph.NewFieldSpec(userslist.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoomID(); ok {
		_spec.SetField(userslist.FieldRoomID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(userslist.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(userslist.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(userslist.FieldPassword, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userslist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsersListUpdateOne is the builder for updating a single UsersList entity.
type UsersListUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsersListMutation
}

// SetRoomID sets the "room_id" field.
func (_u *UsersListUpdateOne) SetRoomID(v string) *UsersListUpdateOne {
	_u.mutation.SetRoomID(v)
	return _u
}

// SetNillableRoomID sets the "room_id" field if the given value is not nil.
func (_u *UsersListUpdateOne) SetNillableRoomID(v *string) *UsersListUpdateOne {
	if v != nil {
		_u.SetRoomID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UsersListUpdateOne) SetUsername(v string) *UsersListUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UsersListUpdateOne) SetNillableUsername(v *string) *UsersListUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UsersListUpdateOne) SetEmail(v string) *UsersListUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UsersListUpdateOne) SetNillableEmail(v *string) *UsersListUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UsersListUpdateOne) SetPassword(v string) *UsersListUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UsersListUpdateOne) SetNillablePassword(v *string) *UsersListUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// Mutation returns the UsersListMutation object of the builder.
func (_u *UsersListUpdateOne) Mutation() *UsersListMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsersListUpdate builder.
func (_u *UsersListUpdateOne) Where(ps ...predicate.UsersList) *UsersListUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsersListUpdateOne) Select(field string, fields ...string) *UsersListUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsersList entity.
func (_u *UsersListUpdateOne) Save(ctx context.Context) (*UsersList, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsersListUpdateOne) SaveX(ctx context.Context) *UsersList {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsersListUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsersListUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsersListUpdateOne) check() error {
	if v, ok := _u.mutation.RoomID(); ok {
		if err := userslist.RoomIDValidator(v); err != nil {
			return &ValidationError{Name: "room_id", err: fmt.Errorf(`ent: validator failed for field "UsersList.room_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := userslist.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UsersList.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := userslist.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UsersList.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := userslist.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "UsersList.password": %w`, err)}
		}
	}
	return nil
}

func (_u *UsersListUpdateOne) sqlSave(ctx context.Context) (_node *UsersList, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userslist.Table, userslist.Columns, sqlgraph.NewFieldSpec(userslist.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsersList.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userslist.FieldID)
		for _, f := range fields {
			if !userslist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userslist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoomID(); ok {
		_spec.SetField(userslist.FieldRoomID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(userslist.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(userslist.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(userslist.FieldPassword, field.TypeString, value)
	}
	_node = &UsersList{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userslist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
