// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "room_id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "text", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "message_room_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[1], MessagesColumns[4]},
			},
		},
	}
	// UsersListsColumns holds the columns for the "users_lists" table.
	UsersListsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "room_id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersListsTable holds the schema information for the "users_lists" table.
	UsersListsTable = &schema.Table{
		Name:       "users_lists",
		Columns:    UsersListsColumns,
		PrimaryKey: []*schema.Column{UsersListsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MessagesTable,
		UsersListsTable,
	}
)

func init() {
}
